# Generated by Django 3.0.3 on 2020-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ville',
            field=models.TextField(blank=True, verbose_name='Ville'),
        ),
    ]
