# Generated by Django 3.0.3 on 2020-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200525_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='Ending date and time'),
        ),
    ]
